"""Create minimal Word template for test_report AppType.

This script creates a minimal test_report.docx with:
- 3 content controls for: title, date, summary

Usage:
    python scripts/create_test_report_template.py
"""

from pathlib import Path

try:
    from docx import Document
    from docx.shared import Pt, RGBColor
    from docx.enum.text import WD_PARAGRAPH_ALIGNMENT
except ImportError:
    print("Error: python-docx not installed")
    print("Run: pip install python-docx")
    exit(1)


def create_test_report_template() -> None:
    """Create minimal test_report.docx template."""

    # Create document
    doc = Document()

    # Add title
    title = doc.add_heading("Test Report", level=1)
    title.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER

    # Add spacing
    doc.add_paragraph()

    # Add title field placeholder
    p1 = doc.add_paragraph()
    p1.add_run("Report Title: ").bold = True
    p1.add_run("[title]")

    # Add date field placeholder
    p2 = doc.add_paragraph()
    p2.add_run("Report Date: ").bold = True
    p2.add_run("[date]")

    # Add spacing
    doc.add_paragraph()

    # Add summary field placeholder
    p3 = doc.add_paragraph()
    p3.add_run("Summary:").bold = True
    doc.add_paragraph("[summary]")

    # Add footer note
    doc.add_paragraph()
    doc.add_paragraph()
    footer = doc.add_paragraph("Generated by Doc Helper Test Report AppType")
    footer.runs[0].font.size = Pt(8)
    footer.runs[0].font.color.rgb = RGBColor(128, 128, 128)
    footer.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER

    # Save template
    template_path = Path("src/doc_helper/app_types/test_report/templates/test_report.docx")
    template_path.parent.mkdir(parents=True, exist_ok=True)
    doc.save(template_path)

    print(f"✓ Created minimal template: {template_path}")
    print("  - Placeholders: [title], [date], [summary]")
    print("  - Note: For full functionality, add content controls with matching tags")


if __name__ == "__main__":
    create_test_report_template()
